// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE7PzOV35SuJCqGQXqxMWmMWaeMc8sE2s',
    appId: '1:316410213877:android:b08dbd88ab9dae02e15cbc',
    messagingSenderId: '316410213877',
    projectId: 'ramro-postal-service-26993',
    storageBucket: 'ramro-postal-service-26993.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd-x3U1AbyAE9VIHtX62uoPGOdCoi9Xe0',
    appId: '1:316410213877:ios:3f7a6d4910284043e15cbc',
    messagingSenderId: '316410213877',
    projectId: 'ramro-postal-service-26993',
    storageBucket: 'ramro-postal-service-26993.firebasestorage.app',
    iosClientId:
        '316410213877-e9aper9bpusbh2l9qhjh52tlgutj58bp.apps.googleusercontent.com',
    iosBundleId: 'com.rps.ramroPostalService',
  );
}
